### PR TITLE
Dynamic Events, Expandable Cards, and some crucial bugs (incomplete) 

### PR DESCRIPTION
**Pull request by zubairabid**
Some image links are broken because of an extension issue.
Date not working (returns None), need to look into that.

### CODE REVIEW

**Comment by zubairabid** [comment]
Fixed the image issue.

**Comment by kaushalvivek** [comment]
Looking into resolving conflicts.

**Comment by kaushalvivek** [comment]
Okay, @zubairabid the issues are complex, resolving will take time. Can you clone the current repo and apply your stashed changes? That will be easier.

**Comment by zubairabid** [comment]
Fixed. Some data in the db needs to be modified. I'll comment it.

In the meanwhile, I found this. Might be useful: https://stackoverflow.com/questions/14665695/git-merge-conflicts-with-our-database-file-multiple-developers

**Comment by 500swapnil** [comment]
Solved in #14

**Pull request closed without merging**
